DROP TABLE IF EXISTS employee CASCADE;
DROP TABLE IF EXISTS employeeofmonths CASCADE;





CREATE TABLE employee(
                         id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         national_id VARCHAR(11) NOT NULL UNIQUE,
                         name VARCHAR(25) NOT NULL,
                         surname VARCHAR(25) NOT NULL,
                         salary INT NOT NULL,
                         start_date DATE NOT NULL,
                         office VARCHAR(35),
                         department  VARCHAR(35)
);

CREATE TABLE employeeofmonths
(

    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    national_id VARCHAR(11)  ,
    name VARCHAR(25) ,
    surname VARCHAR(25) ,
    salary INT ,
    start_date DATE ,
    office VARCHAR(35),
    department  VARCHAR(35)


);


INSERT INTO employee(national_id, name, surname, salary, start_date, department)
VALUES
      ('65283746251','Berk','Balcı',15000,'2000-11-22','Development'),
      ('82736452162','Murat','Kral',20000,'2000-01-22','Marketing'),
      ('98765242536','Mehmed','Aymaz',10000,'2000-01-22','Development'),
      ('28394857653','Derin','Engin',15000,'2000-01-22','Development');